services:

  runner:
    stop_signal: SIGTERM
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: gh_runner
    volumes:
      - "./hostedtools:/opt/hostedtools"
    environment:
      GH_ORG: beepsdev
      GH_TOKEN: ${PAT}
    deploy:
      replicas: 3

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt