  on:
      schedule:
          - cron:  '*/5 * * * *'
      workflow_dispatch:
  jobs:

    refresh_runner:
      runs-on: [self-hosted]
      steps:
        - name: Runner Task
          run: echo "Hello, Please end this runner. :)"
