  on:

      schedule:
          - cron:  '*/30 * * * *'

      push:
          paths:
            - scripts/readme/**
            - .github/workflows/**

      workflow_dispatch:

  permissions: write-all
  
  jobs:

    update_readme:
      runs-on: ubuntu-latest
      steps:

      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '18'

      - name: Generate README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd ./scripts/readme/ && npm install && node readme

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
